-- MySQL Script generated by MySQL Workbench
-- Wed 13 Oct 2021 09:47:19 PM -03
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

-- create database estacionamento;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `cliente_id` VARCHAR(12) NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `rg` INT(11) NOT NULL,
  `Veiculo_veiculo_id` SMALLINT UNSIGNED NOT NULL,
  `Ocorrencia_id_ocorencia` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the address table and the store table where this customer is registered.\n\nBasic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Desocupacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Desocupacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Desocupacao` (
  `desocupacao_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Veiculo_veiculo_id` SMALLINT UNSIGNED NOT NULL,
  `data_saida` DATE NOT NULL,
  `valor_cobrado` DOUBLE NOT NULL,
  PRIMARY KEY (`desocupacao_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the address table and the store table where this customer is registered.\n\nBasic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocorrencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ocorrencia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ocorrencia` (
  `id_ocorencia` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OrderNumber` VARCHAR(10) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OrderDate` DATE NULL,
  `tipo_ocorrencia` VARCHAR(45) NULL,
  `usuario_id_usuario` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_ocorencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocupacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ocupacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ocupacao` (
  `desocupacao_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `UnitPrice` DECIMAL(12) NOT NULL,
  PRIMARY KEY (`desocupacao_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the address table and the store table where this customer is registered.\n\nBasic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Preco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Preco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Preco` (
  `idPreco` INT NOT NULL,
  `Data_Inicial` DATETIME NOT NULL,
  `Cliente_cliente_id` VARCHAR(12) NOT NULL,
  `preco_cobrado` DOUBLE NOT NULL,
... (61 lines left)
